In [9]:
import pandas as pd

In [10]:
benchmark = pd.read_csv(f"../src/assets/comment-intent/v1/benchmark/benchmark.csv")
benchmark

                                               comment     intent
0    كيف طريقة استخدام بطاقه برق الالكترونية في الد...   Question
1                     برق وتكمو جميعها من البنك العربي  Statement
2              برق جميلة صراحة لكن الكاش باك مو قد كدا  Complaint
3    السلام عليكم ورحمه الله وبركاته <br>انا مقيم ب...   Question
4    هل الكاش باك على بطاقة الفيزا فقط أو تشمل مدى ...   Question
..                                                 ...        ...
375                    لا هنت يوجد رسوم تحويل العملة ؟   Question
376  كيف اشحنها اذا شحنته مدى من الراجحي في رسوم علي ؟   Question
377  محمد هل عليها رسوم في اضافة الأموال الى المحفظ...   Question
378  اخيس شي حدك ٥٠٠٠ لليوم سحب او ايدع غير ان اغلب...  Complaint
379  كيف لعبتها مرتين ؟ ؟ احنا مرّة وحدة فقط ولم يس...  Complaint

[380 rows x 2 columns]

In [11]:
label_data_df = pd.read_csv("../src/assets/comment-intent/v1/processed_data/label_data.csv")
label_data_df

,comment_id,comment,intent,source,confidence,latency_ms,cost_usd,stage
0,caabdf91-445b-415c-9afa-8837f1679b79,لارابط ولا اسم ولا صورة ولاشيء,Complaint,gpt-4o-mini,1.0,4503.85,0.000025,training
1,71da5917-ae5d-4085-8eeb-ad79d271c3c6,كودي 6D5A0497DEGCR شغال 100% برق جربته أنا وا ...,Statement,gpt-4o-mini,1.0,2224.73,0.000031,training
2,51618b22-ea4b-42ef-a78d-486448dddda9,CF00EFD9C2GCR كودي اللي يبي يلعب معي ويكسب,Statement,gpt-4o-mini,1.0,1993.03,0.000026,training
3,9fc91184-00fa-461f-8be4-54d19a6bad87,كودي <br>D89FCB27C9GCR<br>اللهم ارزقني وارزق مني,Statement,gpt-4o-mini,1.0,525.87,0.000027,training
4,3a97b51f-e977-4895-9a3b-71968457acfe,اخوي شاركت الكود لا اكثر من شخصين ولا جتني محا...,Question,gpt-4o-mini,1.0,1103.37,0.000026,training
...,...,...,...,...,...,...,...,...
1008,869cef70-6ae4-4a15-a482-d3940a16c7da,أخي الفاضل حاولت أسحب ٥٠ ريال من ماكينه الأهلي...,Complaint,gpt-4o-mini,1.0,755.74,0.000027,training
1009,221e747a-ea7a-40c1-8a8e-d7d32e6af0de,ماذا يستفيد صناع التطبيق من بطاقة برق؟ ما زال ...,Question,gpt-4o-mini,1.0,789.09,0.000026,training
1010,96a84d78-2f90-4b6a-8407-fde585fc879d,كيف يعني جوائز بمليون ريال؟,Question,gpt-4o-mini,1.0,823.40,0.000024,training
1011,348529bd-fa97-4206-b09a-77fd8120fe56,كم خد التحويل اليومى او الشهري,Question,gpt-4o-mini,1.0,608.01,0.000025,training
1012,7d6c661e-c270-41e7-b7e4-b17aae6c66ab,انا عندي مشكلة وهي انا طلبت بطاقتين برق مدى وف...,Question,gpt-4o-mini,1.0,811.46,0.000030,training

In [12]:
common = set(label_data_df["comment"]).intersection(set(benchmark["comment"]))
print(common)

{'ممكن تضيف رمز الدعوة 15D01E6179GCR', 'هل فيه رسوم لمن أحول من بطاقتي الاساسيه لمحفظة برق ؟', '\u200f5 ,محاولات ادا ما جت كلمني.  C4AC76AF92GCR', '4D8E49ECDAGCR الكود حقي لاتقصرون', 'هل أستطيع استخدامها في استئجار السيارات بالخارج كبطاقة إئتمانية  ؟<br>هل استطيع استخدامها في السوبر ماركت مثل بطاقة مدى  ؟'}

In [13]:
benchmark_clean = benchmark[~benchmark["comment"].isin(common)]

In [14]:
benchmark_clean

                                               comment     intent
0    كيف طريقة استخدام بطاقه برق الالكترونية في الد...   Question
1                     برق وتكمو جميعها من البنك العربي  Statement
2              برق جميلة صراحة لكن الكاش باك مو قد كدا  Complaint
3    السلام عليكم ورحمه الله وبركاته <br>انا مقيم ب...   Question
4    هل الكاش باك على بطاقة الفيزا فقط أو تشمل مدى ...   Question
..                                                 ...        ...
375                    لا هنت يوجد رسوم تحويل العملة ؟   Question
376  كيف اشحنها اذا شحنته مدى من الراجحي في رسوم علي ؟   Question
377  محمد هل عليها رسوم في اضافة الأموال الى المحفظ...   Question
378  اخيس شي حدك ٥٠٠٠ لليوم سحب او ايدع غير ان اغلب...  Complaint
379  كيف لعبتها مرتين ؟ ؟ احنا مرّة وحدة فقط ولم يس...  Complaint

[375 rows x 2 columns]

In [15]:
benchmark_clean['intent'].value_counts()

intent
Question      217
Complaint      95
Statement      48
Praise         10
Suggestion      5
Name: count, dtype: int64

In [16]:
benchmark_clean.to_csv("benchmark.csv")